Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -343,40 +343,73 @@ jobs:
             tar -C backend -czvf artifact.tar.gz .
             cd .circleci/ansible
             ansible-playbook -i inventory.txt deploy-backend.yml        
-            
+
   smoke-test:
     docker:
-      - image: amazon/aws-cli
+      - image: python:3.7-alpine3.11 
     steps:
       - checkout
       - run:
           name: Install dependencies
           command: |
-            echo ""
+            apk add --update tar gzip curl
       - run:
           name: Get backend url
           command: |
-            BACKEND_IP=$(curl -H "token: 6a2a4778-e9c2-4af9-b8d8-037bd84c4cd9" --request GET https://api.memstash.io/values/BACKEND_IP)
-            
+            export BACKEND_URL=$(sed --quiet 2p .circleci/ansible/inventory.txt)
       - run:
           name: Backend smoke test.
           command: |
-            echo "${BACKEND_IP}"
-            if curl -sL --fail "http://${BACKEND_IP}:3000/api/status"; then
-              echo "Success"
+            if curl -s https://${BACKEND_URL}:3030/api/status
+            then
+              return 1
             else
-              echo "Fail"
+              return 0
             fi
       - run:
           name: Frontend smoke test.
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-us-west-2.amazonaws.com/index.html"
-            if curl -s ${URL} | grep "Welcome";
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-west-2.amazonaws.com"
+            if curl -s ${URL} | grep "Welcome"
             then
-              exit 0
+              return 1
             else
-              exit 1
+              return 0
             fi
+    
+  # smoke-test:
+  #   docker:
+  #     - image: amazon/aws-cli
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: Install dependencies
+  #         command: |
+  #           echo ""
+  #     - run:
+  #         name: Get backend url
+  #         command: |
+  #           BACKEND_IP=$(curl -H "token: 6a2a4778-e9c2-4af9-b8d8-037bd84c4cd9" --request GET https://api.memstash.io/values/BACKEND_IP)
+            
+  #     - run:
+  #         name: Backend smoke test.
+  #         command: |
+  #           echo "${BACKEND_IP}"
+  #           if curl -sL --fail "http://${BACKEND_IP}:3000/api/status"; then
+  #             echo "Success"
+  #           else
+  #             echo "Fail"
+  #           fi
+  #     - run:
+  #         name: Frontend smoke test.
+  #         command: |
+  #           URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-us-west-2.amazonaws.com/index.html"
+  #           if curl -s ${URL} | grep "Welcome";
+  #           then
+  #             exit 0
+  #           else
+  #             exit 1
+  #           fi
  
 #   cloudfront-update:
 #     docker:
